In [ ]:
from pyArango.connection import *
import pandas as pd

In [ ]:
conn = Connection(username = "root", password = "arango")

In [ ]:
db = conn['GamesDB']

### Query visualizzazioni medie per genere

In [ ]:
sub_query = "LET S = (FOR game IN games FOR i IN game.genres FOR k in game.views RETURN({'name': i.name, 'visuals':k.visuals}))"
query = "FOR i in S COLLECT name = i.name INTO g RETURN({name: name, views_medie: AVG(g[*].i.visuals), sd: STDDEV_SAMPLE(g[*].i.visuals), n:LENGTH(g), l_bound: AVG(g[*].i.visuals)-1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g))), u_bound: AVG(g[*].i.visuals)+1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g)))})"

In [ ]:
Query_genere = sub_query + " " + query

In [ ]:
queryResult = db.AQLQuery(Query_genere, rawResults=True, batchSize=100)

In [ ]:
genere = pd.DataFrame(queryResult)

In [ ]:
genere

,l_bound,n,name,sd,u_bound,views_medie
0,12140.372658,576666,Action-Adventure,27521.064042,12282.438318,12211.405488
1,3814.025323,15834,Block-Breaking,3515.448554,3923.539790,3868.782557
2,10099.126371,64241,Card Game,12430.733202,10291.380938,10195.253654
3,3746.529451,2938,Compilation,3938.943398,4031.394988,3888.962219
4,8599.952912,3581,Educational,7458.668006,9088.543597,8844.248255
5,5448.207577,90769,Fighting,4556.644943,5507.494987,5477.851282
6,2094.525602,242,Gambling,327.866797,2177.143820,2135.834711
7,6470.344651,7787,Minigame Collection,6989.088677,6780.816001,6625.580326
8,49092.946553,88325,MOBA,71484.289027,50035.823127,49564.384840
9,3477.882519,19738,Music/Rhythm,2594.943623,3550.286496,3514.084507
10,4398.712981,82689,Platformer,4086.816496,4454.424800,4426.568891
11,10822.685180,46291,Puzzle,9942.542240,11003.833884,10913.259532
12,8749.913979,379240,Role-Playing,11907.680393,8825.711704,8787.812841
13,30225.076657,342550,Shooter,42108.087491,30507.102949,30366.089803
14,7886.169706,166577,Simulation,8675.275899,7969.492120,7927.830913
15,21681.317875,151488,Sports,44281.506534,22127.301937,21904.309906
16,6173.420109,154055,Strategy,7163.200905,6244.961157,6209.190633
17,3798.152827,600,Text Adventure,3824.022243,4410.123840,4104.138333

In [ ]:
genere.to_csv(r"/home/andrea/Scrivania/genere.csv", index = False)

### Query visualizzazioni medie per game modes

In [ ]:
sub_query = "LET S = (FOR game IN games FOR k in game.views RETURN({'name': game.game_modes, 'visuals':k.visuals}))"
query = "FOR i in S COLLECT name = i.name INTO g RETURN({name: name, views_medie: AVG(g[*].i.visuals), sd: STDDEV_SAMPLE(g[*].i.visuals), n:LENGTH(g), l_bound: AVG(g[*].i.visuals)-1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g))), u_bound: AVG(g[*].i.visuals)+1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g)))})"

In [ ]:
Query_game_modes = sub_query + " " + query
queryResult = db.AQLQuery(Query_game_modes, rawResults=True, batchSize=100)

In [ ]:
games_modes = pd.DataFrame(queryResult)

In [ ]:
games_modes

,l_bound,n,name,sd,u_bound,views_medie
0,20700.228784,779988,Gioco sia Single Player che Multiplayer,43246.139526,20892.179374,20796.204079
1,20112.975030,369572,Gioco solo Multiplayer,25183.055591,20275.359676,20194.167353
2,4636.899605,196814,Gioco solo Single Player,5095.617610,4681.924727,4659.412166

In [ ]:
games_modes.to_csv(r"/home/andrea/Scrivania/game_modes.csv", index = False)

### Query visualizzazioni medie per numero di personaggi

In [ ]:
sub_query = "LET S = (FOR game IN games FOR k in game.views RETURN({'name': game.characters, 'visuals':k.visuals}))"
query = "FOR i in S COLLECT name = i.name INTO g RETURN({name: name, views_medie: AVG(g[*].i.visuals), sd: STDDEV_SAMPLE(g[*].i.visuals), n:LENGTH(g), l_bound: AVG(g[*].i.visuals)-1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g))), u_bound: AVG(g[*].i.visuals)+1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g)))})"
Query_characters = sub_query + " " + query

In [ ]:
queryResult = db.AQLQuery(Query_characters, rawResults=True, batchSize=100)

In [ ]:
characters = pd.DataFrame(queryResult)

In [ ]:
characters

        l_bound       n        name            sd       u_bound   views_medie
0  10605.120821  481459           0  17095.483197  10701.700952  10653.410886
1  24330.129649  176089    da 1 a 5  41867.619713  24721.239022  24525.684336
2  10698.075699  161477  da 10 a 20  12414.040190  10819.175625  10758.625662
3  13106.497857  143222   da 5 a 10  23587.284977  13350.817933  13228.657895
4  29825.093787  384127   più di 20  53189.538520  30161.508415  29993.301101

In [ ]:
characters.to_csv(r"/home/andrea/Scrivania/personaggi.csv", index = False)

### Query visualizzazioni medie per piattaforma

In [ ]:
sub_query = "LET S = (FOR game IN games FOR k in game.views RETURN({'name': game.platforms, 'visuals':k.visuals}))"
query = "FOR i in S COLLECT name = i.name INTO g RETURN({name: name, views_medie: AVG(g[*].i.visuals), sd: STDDEV_SAMPLE(g[*].i.visuals), n:LENGTH(g), l_bound: AVG(g[*].i.visuals)-1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g))), u_bound: AVG(g[*].i.visuals)+1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g)))})"
query_platforms = sub_query + " " + query

In [ ]:
queryResult = db.AQLQuery(query_platforms, rawResults=True, batchSize=100)

In [ ]:
platforms = pd.DataFrame(queryResult)

In [ ]:
platforms

,l_bound,n,name,sd,u_bound,views_medie
0,3368.056094,8528,giochi per Console e Console Portatili,1889.766709,3448.273878,3408.164986
1,10744.405542,74,giochi per Console e Smartphone,1559.971540,11455.270134,11099.837838
2,2582.549985,168,"giochi per Console, Console Portatili e Smartp...",784.097298,2819.688111,2701.119048
3,17165.428923,616909,giochi per PC e Console,33036.383708,17330.308937,17247.868930
4,2706.273512,6628,giochi per PC e Console Portatili,1525.420566,2779.722263,2742.997888
5,13840.085874,77525,giochi per PC e Smartphone,11849.534670,14006.912926,13923.499400
6,5130.652633,8801,"giochi per PC, Console e Console Portatili",3038.819605,5257.629608,5194.141120
7,35290.690564,86675,"giochi per PC, Console e Smartphone",52766.903927,35993.278608,35641.984586
8,2348.424458,2165,"giochi per PC, Console Portatili e Smartphone",800.040536,2415.825888,2382.125173
9,45243.130218,27654,"giochi per tutte le piattaforme: PC, Console, ...",45140.339957,46307.204418,45775.167318
10,4998.981265,149886,giochi solo per Console,4001.511931,5039.497553,5019.239409
11,4627.664755,5069,giochi solo per Console Portatili,3850.676990,4839.677521,4733.671138
12,24094.503952,303686,giochi solo per PC,46291.825683,24423.793533,24259.148742
13,5308.132399,52606,giochi solo per Smartphone,8902.201173,5460.280253,5384.206326

In [ ]:
platforms.to_csv(r"/home/andrea/Scrivania/platforms.csv", index = False)

### Visualizzazioni medie per age rating

In [ ]:
sub_query = "LET S = (FOR game IN games FOR k in game.views RETURN({'name': game.age_ratings, 'visuals':k.visuals}))"
query = "FOR i in S COLLECT name = i.name INTO g RETURN({name: name, views_medie: AVG(g[*].i.visuals), sd: STDDEV_SAMPLE(g[*].i.visuals), n:LENGTH(g), l_bound: AVG(g[*].i.visuals)-1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g))), u_bound: AVG(g[*].i.visuals)+1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g)))})"
query_age_rating = sub_query + " " + query

In [ ]:
queryResult = db.AQLQuery(query_age_rating, rawResults=True, batchSize=100)
age_rating = pd.DataFrame(queryResult)
age_rating

,l_bound,n,name,sd,u_bound,views_medie
0,20357.057480,634300,giochi per adolescenti,39652.150506,20552.224062,20454.640771
1,22155.966308,368811,giochi per adulti,40329.683580,22416.287155,22286.126732
2,9911.459822,340254,giochi per tutti,18049.083495,10032.753901,9972.106861
3,4545.370242,3009,RP,5137.872388,4912.532715,4728.951479

In [ ]:
age_rating.to_csv(r"/home/andrea/Scrivania/age_rating.csv", index = False)

### Query pubblication year

In [ ]:
sub_query = "LET S = (FOR game IN games FOR k in game.views RETURN({'name': game.pubblication_year, 'visuals':k.visuals}))"
query = "FOR i in S COLLECT name = i.name INTO g RETURN({name: name, views_medie: AVG(g[*].i.visuals), sd: STDDEV_SAMPLE(g[*].i.visuals), n:LENGTH(g), l_bound: AVG(g[*].i.visuals)-1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g))), u_bound: AVG(g[*].i.visuals)+1.96*(STDDEV_SAMPLE(g[*].i.visuals) / SQRT(LENGTH(g)))})"
query_pubblication_year = sub_query + " " + query

In [ ]:
queryResult = db.AQLQuery(query_pubblication_year, rawResults=True, batchSize=100)
pubblication_year = pd.DataFrame(queryResult)
pubblication_year.head()

       l_bound    n  name           sd      u_bound  views_medie
0  3612.000000    3  1975     0.000000  3612.000000  3612.000000
1  2567.804253  222  1977   536.906214  2709.060612  2638.432432
2  2186.452547  152  1978   339.142621  2294.284295  2240.368421
3  1805.541397   34  1979    74.863726  1855.870368  1830.705882
4  6529.386448  649  1986  4000.850049  7145.011087  6837.198767

In [ ]:
pubblication_year.to_csv(r"/home/andrea/Scrivania/pubblication_year.csv", index = False)